version: "3.8"

services:
  estudo-app-test:
    image: atilarampazo/api
    user: "root:root"
    build:
      context: .
      target: ci
    command:
        sh -c "php artisan test"
    env_file:
      - ./docker/docker-compose-env/application.env
    volumes:
      - ./:/var/www/html/
    restart: unless-stopped

