name: Estudo CI/CD

on:
  push:
    branches:
      - "qa"
jobs:
  application-tests:
    name: Test Application
    runs-on:  ubuntu-latest

    steps:

    - uses: whoan/docker-build-with-cache-action@v5
    - name: Build and Cache image
      with:
        compose_file: docker-compose.yml
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        echo ---Building and starting up docker---
        docker-compose -f docker-compose.yml  -p  testing up -d
        echo ---Containers  up---
    - name: Run Test
      run: |
        echo  --- Runing test cases ---
        docker exec estudo-app composer test
        echo --- Completed test cases --
