name: Estudo CI/CD

on:
  push:
    branches:
      - "qa"
jobs:
  application-tests:
    name: Estudo Github Actions
    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build 🥳 and Run Tests 🧪 
      run: |
        echo ---Building / Run Test---
        docker-compose run  --rm estudo-app-test


