name: Estudo CI/CD

on:
  push:
    branches:
      - "qa"
jobs:
  application-tests:
    name: Test Application
    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        echo ---Building and starting up docker---
        docker-compose -f docker-compose.yml up -d
        echo ---Containers  up---
    - name: Run Test
      run: |
        echo  --- Runing test cases ---
        docker exec estudo-app php artisan test
        echo --- Completed test cases --
